### ISSUE TITLE
ValueError: 'd223af7fbf34f5a5111bb1542d8b925c'  is not in list

### ISSUE THREAD

**Issue by stsmall** [simonhmartin/twisst#1]
Hi @simonhmartin,
Thank you for a great program!
I have run twisst many times without an error, but now seem to be receiving error messages on a few trees. Initially I used BioNJ trees with the same individual sample labels and had no issues. These BioNJ trees did not have bootstrap values. I have switched over to using max likelihood trees generated with RAxML and FastTree. FastTree produces aLRT support values, could this be causing the below errors?
thanks,
scott

Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/s/ssmall2/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/afs/crc.nd.edu/user/s/ssmall2/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/afs/crc.nd.edu/user/s/ssmall2/programs_that_work/twisst/run_twisst_parallel.py", line 44, in weightTree_wrapper
    weightsData = twisst.weightTreeSimp(tree=tree, taxa=taxa, taxonNames=taxonNames, topos=topos, getDists=getDists, abortCutoff=args.abortCutoff)
  File "/afs/crc.nd.edu/user/s/ssmall2/programs_that_work/twisst/twisst.py", line 383, in weightTreeSimp
    x = topoIDs.index(prunedID)
ValueError: 'dd1ccb7098f363bc0cab5e347c4987a7' is not in list
2234 trees queued | 2182 results received | 1664 results written.
4368 trees queued | 4317 results received | 1664 results written.
Process Process-4:
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/s/ssmall2/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/afs/crc.nd.edu/user/s/ssmall2/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/afs/crc.nd.edu/user/s/ssmall2/programs_that_work/twisst/run_twisst_parallel.py", line 44, in weightTree_wrapper
    weightsData = twisst.weightTreeSimp(tree=tree, taxa=taxa, taxonNames=taxonNames, topos=topos, getDists=getDists, abortCutoff=args.abortCutoff)
  File "/afs/crc.nd.edu/user/s/ssmall2/programs_that_work/twisst/twisst.py", line 383, in weightTreeSimp
    x = topoIDs.index(prunedID)
ValueError: '5b339154d31bc114b9db4f34f955306e' is not in list
6528 trees queued | 6476 results received | 1664 results written.
Process Process-1:
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/s/ssmall2/anaconda2/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/afs/crc.nd.edu/user/s/ssmall2/anaconda2/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/afs/crc.nd.edu/user/s/ssmall2/programs_that_work/twisst/run_twisst_parallel.py", line 44, in weightTree_wrapper
    weightsData = twisst.weightTreeSimp(tree=tree, taxa=taxa, taxonNames=taxonNames, topos=topos, getDists=getDists, abortCutoff=args.abortCutoff)
  File "/afs/crc.nd.edu/user/s/ssmall2/programs_that_work/twisst/twisst.py", line 383, in weightTreeSimp
    x = topoIDs.index(prunedID)
ValueError: 'd223af7fbf34f5a5111bb1542d8b925c' is not in list

**Comment by stsmall** [comment]
UPDATE:
I removed the aLRT values by rerunning a test using FastTree with the option of -nosupport. However, I am still getting the error at 3 very specific trees. Here is 1 of the trees causing the error:

(((((longipalpusC_15:0.00055,(longipalpusC_4:0.00055,(longipalpusC_11:0.00055,((parensis_KwaF769:0.00055,parensis_KwaF851:0.00055):0.00055,(longipalpusC_551_12533:0.00055,(parensis_KwaF766:0.00115,(parensis_KwaF762:0.00055,((parensis_KwaF767:0.0,parensis_KwaF835:0.0):0.00055,(parensis_KwaF761:0.00055,parensis_KwaF768:0.00555):0.00055):0.00153):0.00189):0.00059):0.00059):0.00055):0.00055):0.00055):0.00055,longipalpusC_13:0.00055):0.00055,longipalpusC_16:0.00055):0.00055,(longipalpusC_551_12634:0.00208,longipalpusC_12:0.00055):0.00054):0.00142,vaneedeni_KwaF783:0.00055,(vaneedeni_KwaF773:0.00055,(vaneedeni_KwaF775:0.00055,(vaneedeni_KwaF780:0.00055,((vaneedeni_KwaF782:0.00055,vaneedeni_KwaF786:0.00569):0.00055,(vaneedeni_KwaF774:0.00055,(((funestuscf_MALF98_2:0.00055,(funestuscf_MALAF105_7:0.00055,funestuscf_MALAF99_4:0.00055):0.00055):0.01010,(funestus_Ken4590:0.00053,(rivulorum_F790:0.26756,(((funestus_Ugf401:0.00055,(funestus_GhaF264:0.00055,funestus_GhaF265:0.00055):0.00055):0.00055,funestus_Ugf399:0.00055):0.00055,(funestus_Ugf403:0.00108,(funestus_TanF561:0.00055,(funestus_TanF601:0.00055,((funestus_MozF260:0.0,funestus_MozF29:0.0):0.00055,((funestus_MozF123:0.0,funestus_MozF35:0.0,funestus_Zam281:0.0):0.00054,funestus_MozF804:0.00055):0.00053):0.00415):0.00096):0.00058):0.00104):0.00123):0.00053):0.00287):0.01492,vaneedeni_KwaF784:0.00053):0.00054):0.00087):0.00055):0.00055):0.00055):0.00055);

**Comment by simonhmartin** [comment]
Dear Scott,
Apologies - I missed this email from you.
I will look into this issue and try to figure out what's gone wrong.
Best wishes,
Simon
