### ISSUE TITLE
Fatal error when writing weights file

### ISSUE THREAD

**Issue by drdna** [simonhmartin/twisst#5]
The twisst run appears to be completing but then fails when it tries to write the outfile:

Traceback (most recent call last):
  File "twisst.py", line 690, in <module>
    for x in range(nTopos): weightsFile.write("#topo" + str(x+1) + " " + topos[x].write(format = 9) + "\n") 
  File "/home/farman/anaconda_ete/lib/python3.6/gzip.py", line 260, in write
    data = memoryview(data)
TypeError: memoryview: a bytes-like object is required, not 'str'

**Comment by simonhmartin** [comment]
Are you running with python 3? Twisst is currently written only for python 2.

**Comment by drdna** [comment]
Hi Simon,

Thanks for you response. I thought it was running in python2 but when I checked it was still under python3.  Having problems with python2 now - segmentation fault - will try and troubleshoot.

Mark



On Sep 12, 2018, at 6:38 PM, Simon martin <notifications@github.com<mailto:notifications@github.com>> wrote:


Are you running with python 3? Twisst is currently written only for python 2.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsimonhmartin%2Ftwisst%2Fissues%2F5%23issuecomment-420821402&data=02%7C01%7Cmark.farman%40uky.edu%7Cfc7b5817d65b4a12cc6408d6190070d0%7C2b30530b69b64457b818481cb53d42ae%7C0%7C0%7C636723887014738145&sdata=kpNsBRzIbepquqmV3BtIztdvWs32sIn3aQf3bc4E%2Fcw%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADFKDRYHkmeha_dbmgodeTNg2eBj7su8ks5uaYzYgaJpZM4WlvXO&data=02%7C01%7Cmark.farman%40uky.edu%7Cfc7b5817d65b4a12cc6408d6190070d0%7C2b30530b69b64457b818481cb53d42ae%7C0%7C0%7C636723887014748158&sdata=n9Sctg4QNFPHfFiGEJFlH%2FzyulRYBZ2mfLDyOExtPIY%3D&reserved=0>.

Mark L. Farman
Professor, Department of Plant Pathology
Associate Director, UK-Healthcare Genomics
225 Plant Science Building
1405 Veteran's Dr.
University of Kentucky
Lexington, KY 40546 USA
tel:  (859) 218-0728
fax:  (859) 323-1961

**Comment by drdna** [comment]
Hi Simon,

As a follow-up to my previous email, I was wondering of you had any thoughts on why twisst was failing to produce any output for several tree topologies at taxa values of 6, 7 and 8?

Cheers,

Mark

Mark L. Farman
Professor, Department of Plant Pathology
Associate Director, UK-Healthcare Genomics
225 Plant Science Building
1405 Veteran's Dr.
University of Kentucky
Lexington, KY 40546 USA
tel:  (859) 218-0728
fax:  (859) 323-1961

**Comment by simonhmartin** [comment]
Hi Mark,
Can you expand on what you mean by "failing to produce any output for several tree topologies"? Is there no output file? or is it missing columns?
I have never tried to use Twisst for 8 taxa, because the output file should have 135135 columns! In theory it is possible to specify just the topologies you are interested in as additional input file, but that feature is untested.
-Simon

**Comment by drdna** [comment]
Hi Simon,

OK, in doing some “troubleshooting, it appears that it was an issue with the Linux environment running on the supercomputer I am using. I don’t normally use this machine but decided to try it for the twisst runs. For some reason, when I use cat, less, more, tail, etc. to view the output files, it only displays a fraction of the weights columns that are in the output file. However, when I download to my local machine, or awk the fields in the last line of data, everything is present in the file.  Not sure what’s happening but it's very strange because it’s only the weights line has this problem.

Sorry for troubling you with this.

Mark

On Sep 26, 2018, at 5:04 AM, Simon martin <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Mark,
Can you expand on what you mean by "failing to produce any output for several tree topologies"? Is there no output file? or is it missing columns?
I have never tried to use Twisst for 8 taxa, because the output file should have 135135 columns! In theory it is possible to specify just the topologies you are interested in as additional input file, but that feature is untested.
-Simon

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsimonhmartin%2Ftwisst%2Fissues%2F5%23issuecomment-424641682&data=02%7C01%7Cmark.farman%40uky.edu%7Cc2cbb99df5aa4752829508d6238f1b89%7C2b30530b69b64457b818481cb53d42ae%7C0%7C0%7C636735494878167065&sdata=NzvgG3TUPoJk8N7t1oUPcSXtVjFvcpMh%2BxKhmo1caDA%3D&reserved=0>, or mute the thread<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADFKDQFhHBbequQvcttfD_SzrIlLrEd2ks5ue0MtgaJpZM4WlvXO&data=02%7C01%7Cmark.farman%40uky.edu%7Cc2cbb99df5aa4752829508d6238f1b89%7C2b30530b69b64457b818481cb53d42ae%7C0%7C0%7C636735494878167065&sdata=Eh0ysTA88e4HJycM0boGmGJlgtzDYYWOoTE%2B3T6mKa8%3D&reserved=0>.

Mark L. Farman
Professor, Department of Plant Pathology
Associate Director, UK-Healthcare Genomics
225 Plant Science Building
1405 Veteran's Dr.
University of Kentucky
Lexington, KY 40546 USA
tel:  (859) 218-0728
fax:  (859) 323-1961
